project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]
##################################################
from django.urls import include

urlpatterns += [
    path('theme/', include('theme.urls')),
]

theme/urls.py
from django.urls import path
from theme.views import *


app_name = 'theme'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('index2', IndexView2.as_view(), name='index2'),
    path('index3', IndexView3.as_view(), name='index3'),

    path('error_400', ErrorPage400View.as_view(), name='error_400'),
    path('error_403', ErrorPage403View.as_view(), name='error_403'),
    path('error_404', ErrorPage404View.as_view(), name='error_404'),
    path('error_500', ErrorPage500View.as_view(), name='error_500'),
    path('error_503', ErrorPage503View.as_view(), name='error_503'),

    path('form_basic', FormBasicView.as_view(), name='form_basic'),
    path('advanced_component', FormAdvanceComponentView.as_view(), name='advanced_component'),
    path('form_wizard', FormWizardView.as_view(), name='form_wizard'),
    path('html5_editor', FormHtml5EditorView.as_view(), name='html5_editor'),
    path('form_pickers', FormPickersView.as_view(), name='form_pickers'),
    path('image_cropper', FormImageCropperView.as_view(), name='image_cropper'),
    path('image_dropzone', FormImageDropzoneView.as_view(), name='image_dropzone'),

    path('basic_table', TableBasicView.as_view(), name='basic_table'),
    path('datatable', TableDataView.as_view(), name='datatable'),

    path('calendar', CalendarView.as_view(), name='calendar'),

    path('ui_buttons', UIButtonsView.as_view(), name='ui_buttons'),
    path('ui_cards', UICardsView.as_view(), name='ui_cards'),
    path('ui_cards_hover', UICardsHoverView.as_view(), name='ui_cards_hover'),
    path('ui_modals', UIModalsView.as_view(), name='ui_modals'),
    path('ui_tabs', UITabsView.as_view(), name='ui_tabs'),
    path('ui_tooltip_popover', UITooltipPopoverView.as_view(), name='ui_tooltip_popover'),
    path('ui_sweet_alert', UISweetAlertView.as_view(), name='ui_sweet_alert'),
    path('ui_notification', UINotificationView.as_view(), name='ui_notification'),
    path('ui_timeline', UITimelineView.as_view(), name='ui_timeline'),
    path('ui_progressbar', UIProgressbarView.as_view(), name='ui_progressbar'),
    path('ui_typography', UITypographyView.as_view(), name='ui_typography'),
    path('ui_list_group', UIListGroupView.as_view(), name='ui_list_group'),
    path('ui_range_slider', UIRangeSliderView.as_view(), name='ui_range_slider'),
    path('ui_carousel', UICarouselView.as_view(), name='ui_carousel'),

    path('icon_bootstrap', IconBootstrapView.as_view(), name='icon_bootstrap'),
    path('icon_font_awesome', IconFontAwesomeView.as_view(), name='icon_font_awesome'),
    path('icon_foundation', IconFoundationView.as_view(), name='icon_foundation'),
    path('icon_ionicons', IconIoniconsView.as_view(), name='icon_ionicons'),
    path('icon_themify', IconThemifyView.as_view(), name='icon_themify'),
    path('icon_custom', IconCustomView.as_view(), name='icon_custom'),

    path('highchart', HighchartView.as_view(), name='highchart'),
    path('knobchart', KnobchartView.as_view(), name='knobchart'),
    path('jvectormap', JvectormapView.as_view(), name='jvectormap'),
    path('apexchart', ApexchartView.as_view(), name='apexchart'),

    path('chat', ChatView.as_view(), name='chat'),

    path('invoice', InvoiceView.as_view(), name='invoice'),

    path('sitemap', SitemapView.as_view(), name='sitemap'),
    
    path('comming_soon', CommingSoonView.as_view(), name='comming_soon'),

    path('introduction', IntroductionView.as_view(), name='introduction'),
    path('getting_started', GettingStartedView.as_view(), name='getting_started'),
    path('color_settings', ColorSettingsView.as_view(), name='color_settings'),
    path('third_party_plugins', ThirdPartyPluginsView.as_view(), name='third_party_plugins'),

    path('login', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('forgot_password', ForgotPasswordView.as_view(), name='forgot_password'),
    path('reset_password', ResetPasswordView.as_view(), name='reset_password'),
]

theme/views.py
from django.views.generic import TemplateView
from django.shortcuts import HttpResponse

class IndexView(TemplateView):
    template_name = 'mock/dashboards/index.html'

class IndexView2(TemplateView):
    template_name = 'mock/dashboards/index2.html'

class IndexView3(TemplateView):
    template_name = 'mock/dashboards/index3.html'


class ErrorPage400View(TemplateView):
    template_name = 'mock/error_pages/400.html'

class ErrorPage403View(TemplateView):
    template_name = 'mock/error_pages/403.html'

class ErrorPage404View(TemplateView):
    template_name = 'mock/error_pages/404.html'

class ErrorPage500View(TemplateView):
    template_name = 'mock/error_pages/500.html'

class ErrorPage503View(TemplateView):
    template_name = 'mock/error_pages/503.html'


class FormBasicView(TemplateView):
    template_name = 'mock/forms/form-basic.html'

class FormAdvanceComponentView(TemplateView):
    template_name = 'mock/forms/advanced-components.html'

class FormWizardView(TemplateView):
    template_name = 'mock/forms/form-wizard.html'

class FormHtml5EditorView(TemplateView):
    template_name = 'mock/forms/html5-editor.html'

class FormPickersView(TemplateView):
    template_name = 'mock/forms/form-pickers.html'

class FormImageCropperView(TemplateView):
    template_name = 'mock/forms/image-cropper.html'
    
class FormImageDropzoneView(TemplateView):
    template_name = 'mock/forms/image-dropzone.html'

    def post(self, request, *args, **kwargs):
        return HttpResponse('123123')
    

class TableBasicView(TemplateView):
    template_name = 'mock/tables/basic-table.html'

class TableDataView(TemplateView):
    template_name = 'mock/tables/datatable.html'


class CalendarView(TemplateView):
    template_name = 'mock/calendar/calendar.html'


class UIButtonsView(TemplateView):
    template_name = 'mock/ui_elements/ui-buttons.html'

class UICardsView(TemplateView):
    template_name = 'mock/ui_elements/ui-cards.html'

class UICardsHoverView(TemplateView):
    template_name = 'mock/ui_elements/ui-cards-hover.html'

class UIModalsView(TemplateView):
    template_name = 'mock/ui_elements/ui-modals.html'

class UITabsView(TemplateView):
    template_name = 'mock/ui_elements/ui-tabs.html'

class UITooltipPopoverView(TemplateView):
    template_name = 'mock/ui_elements/ui-tooltip-popover.html'

class UISweetAlertView(TemplateView):
    template_name = 'mock/ui_elements/ui-sweet-alert.html'

class UINotificationView(TemplateView):
    template_name = 'mock/ui_elements/ui-notification.html'

class UITimelineView(TemplateView):
    template_name = 'mock/ui_elements/ui-timeline.html'

class UIProgressbarView(TemplateView):
    template_name = 'mock/ui_elements/ui-progressbar.html'

class UITypographyView(TemplateView):
    template_name = 'mock/ui_elements/ui-typography.html'

class UIListGroupView(TemplateView):
    template_name = 'mock/ui_elements/ui-list-group.html'

class UIRangeSliderView(TemplateView):
    template_name = 'mock/ui_elements/ui-range-slider.html'

class UICarouselView(TemplateView):
    template_name = 'mock/ui_elements/ui-carousel.html'


class IconBootstrapView(TemplateView):
    template_name = 'mock/icons/bootstrap-icon.html'

class IconFontAwesomeView(TemplateView):
    template_name = 'mock/icons/font-awesome.html'

class IconFoundationView(TemplateView):
    template_name = 'mock/icons/foundation.html'

class IconIoniconsView(TemplateView):
    template_name = 'mock/icons/ionicons.html'

class IconThemifyView(TemplateView):
    template_name = 'mock/icons/themify.html'

class IconCustomView(TemplateView):
    template_name = 'mock/icons/custom-icon.html'


class HighchartView(TemplateView):
    template_name = 'mock/charts/highchart.html'

class KnobchartView(TemplateView):
    template_name = 'mock/charts/knob-chart.html'

class JvectormapView(TemplateView):
    template_name = 'mock/charts/jvectormap.html'

class ApexchartView(TemplateView):
    template_name = 'mock/charts/apexcharts.html'


class ChatView(TemplateView):
    template_name = 'mock/chat/chat.html'


class InvoiceView(TemplateView):
    template_name = 'mock/invoice/invoice.html'

class SitemapView(TemplateView):
    template_name = 'mock/sitemap/sitemap.html'

class CommingSoonView(TemplateView):
    template_name = 'mock/comming_soon.html'


class IntroductionView(TemplateView):
    template_name = 'mock/documentation/introduction.html'

class GettingStartedView(TemplateView):
    template_name = 'mock/documentation/getting-started.html'

class ColorSettingsView(TemplateView):
    template_name = 'mock/documentation/color-settings.html'

class ThirdPartyPluginsView(TemplateView):
    template_name = 'mock/documentation/third-party-plugins.html'


class LoginView(TemplateView):
    template_name = 'mock/additional_pages/login.html'

class RegisterView(TemplateView):
    template_name = 'mock/additional_pages/register.html'

class ForgotPasswordView(TemplateView):
    template_name = 'mock/additional_pages/forgot-password.html'

class ResetPasswordView(TemplateView):
    template_name = 'mock/additional_pages/reset-password.html'

theme/templates/mock/additional_pages/forgot-password.html
{% extends 'mock/layouts/auth_base.html' %}
{% load static %}

{% block 'title' %} Forgot Password {% endblock 'title' %}


{% block 'css' %}
<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/core.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/icon-font.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/style.css' %}" />
{% endblock 'css' %}

{% block 'content' %}
<body>
	<div class="login-header box-shadow">
		<div class="container-fluid d-flex justify-content-between align-items-center">
			<div class="brand-logo">
				<a href="{% url 'theme:login' %}">
					<img src="{% static 'vendors/images/deskapp-logo.svg' %}" alt="" />
				</a>
			</div>
			<div class="login-menu">
				<ul>
					<li><a href="#">Login</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="login-wrap d-flex align-items-center flex-wrap justify-content-center">
		<div class="container">
			<div class="row align-items-center">
				<div class="col-md-6">
					<img src="{% static 'vendors/images/forgot-password.png' %}" alt="" />
				</div>
				<div class="col-md-6">
					<div class="login-box bg-white box-shadow border-radius-10">
						<div class="login-title">
							<h2 class="text-center text-primary">Forgot Password</h2>
						</div>
						<h6 class="mb-20">
							Enter your email address to reset your password
						</h6>
						<form>
							<div class="input-group custom">
								<input type="text" class="form-control form-control-lg" placeholder="Email" />
								<div class="input-group-append custom">
									<span class="input-group-text"><i class="fa fa-envelope-o" aria-hidden="true"></i></span>
								</div>
							</div>
							<div class="row align-items-center">
								<div class="col-5">
									<div class="input-group mb-0">
										<!--
											use code for form submit
											<input class="btn btn-primary btn-lg btn-block" type="submit" value="Submit">
										-->
										<a class="btn btn-primary btn-lg btn-block" href="{% url 'theme:reset_password' %}">Submit</a>
									</div>
								</div>
								<div class="col-2">
									<div class="font-16 weight-600 text-center" data-color="#707373">
										OR
									</div>
								</div>
								<div class="col-5">
									<div class="input-group mb-0">
										<a class="btn btn-outline-primary btn-lg btn-block" href="{% url 'theme:login' %}">Login</a>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	{% include 'mock/includes/modal.html' %}

	<!-- js -->
	<script src="{% static 'vendors/scripts/core.js' %}"></script>
	<script src="{% static 'vendors/scripts/script.min.js' %}"></script>
	<script src="{% static 'vendors/scripts/process.js' %}"></script>
	<script src="{% static 'vendors/scripts/layout-settings.js' %}"></script>
</body>
{% endblock 'content' %}

theme/templates/mock/additional_pages/login.html
{% extends 'mock/layouts/auth_base.html' %}
{% load static %}

{% block 'title' %} Login {% endblock 'title' %}


{% block 'css' %}
<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/core.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/icon-font.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/style.css' %}" />
{% endblock 'css' %}

{% block 'content' %}
<body class="login-page">
	<div class="login-header box-shadow">
		<div class="container-fluid d-flex justify-content-between align-items-center">
			<div class="brand-logo">
				<a href="{% url 'theme:login' %}">
					<img src="{% static 'vendors/images/deskapp-logo.svg' %}" alt="" />
				</a>
			</div>
			<div class="login-menu">
				<ul>
					<li><a href="{% url 'theme:register' %}">Register</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="login-wrap d-flex align-items-center flex-wrap justify-content-center">
		<div class="container">
			<div class="row align-items-center">
				<div class="col-md-6 col-lg-7">
					<img src="{% static 'vendors/images/login-page-img.png' %}" alt="" />
				</div>
				<div class="col-md-6 col-lg-5">
					<div class="login-box bg-white box-shadow border-radius-10">
						<div class="login-title">
							<h2 class="text-center text-primary">Login To DeskApp</h2>
						</div>
						<form>
							<div class="select-role">
								<div class="btn-group btn-group-toggle" data-toggle="buttons">
									<label class="btn active">
										<input type="radio" name="options" id="admin" />
										<div class="icon">
											<img src="{% static 'vendors/images/briefcase.svg' %}" class="svg" alt="" />
										</div>
										<span>I'm</span>
										Manager
									</label>
									<label class="btn">
										<input type="radio" name="options" id="user" />
										<div class="icon">
											<img src="{% static 'vendors/images/person.svg' %}" class="svg" alt="" />
										</div>
										<span>I'm</span>
										Employee
									</label>
								</div>
							</div>
							<div class="input-group custom">
								<input type="text" class="form-control form-control-lg" placeholder="Username" />
								<div class="input-group-append custom">
									<span class="input-group-text"><i class="icon-copy dw dw-user1"></i></span>
								</div>
							</div>
							<div class="input-group custom">
								<input type="password" class="form-control form-control-lg" placeholder="**********" />
								<div class="input-group-append custom">
									<span class="input-group-text"><i class="dw dw-padlock1"></i></span>
								</div>
							</div>
							<div class="row pb-30">
								<div class="col-6">
									<div class="custom-control custom-checkbox">
										<input type="checkbox" class="custom-control-input" id="customCheck1" />
										<label class="custom-control-label" for="customCheck1">Remember</label>
									</div>
								</div>
								<div class="col-6">
									<div class="forgot-password">
										<a href="{% url 'theme:forgot_password' %}">Forgot Password</a>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-12">
									<div class="input-group mb-0">
										<!--
											use code for form submit
											<input class="btn btn-primary btn-lg btn-block" type="submit" value="Sign In">
										-->
										<a class="btn btn-primary btn-lg btn-block" href="{% url 'theme:index' %}">Sign In</a>
									</div>
									<div class="font-16 weight-600 pt-10 pb-10 text-center" data-color="#707373">
										OR
									</div>
									<div class="input-group mb-0">
										<a class="btn btn-outline-primary btn-lg btn-block" href="{% url 'theme:register' %}">Register To Create
											Account</a>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

	{% include 'mock/includes/modal.html' %}
	
	<!-- js -->
	<script src="{% static 'vendors/scripts/core.js' %}"></script>
	<script src="{% static 'vendors/scripts/script.min.js' %}"></script>
	<script src="{% static 'vendors/scripts/process.js' %}"></script>
	<script src="{% static 'vendors/scripts/layout-settings.js' %}"></script>
</body>
{% endblock 'content' %}

theme/templates/mock/additional_pages/register.html
{% extends 'mock/layouts/auth_base.html' %}
{% load static %}

{% block 'title' %} Register {% endblock 'title' %}


{% block 'css' %}
<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/core.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/icon-font.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'src/plugins/jquery-steps/jquery.steps.css' %}" />
{% endblock 'css' %}

{% block 'content' %}
<body class="login-page">
	<div class="login-header box-shadow">
		<div class="container-fluid d-flex justify-content-between align-items-center">
			<div class="brand-logo">
				<a href="{% url 'theme:login' %}">
					<img src="{% static 'vendors/images/deskapp-logo.svg' %}" alt="" />
				</a>
			</div>
			<div class="login-menu">
				<ul>
					<li><a href="{% url 'theme:login' %}">Login</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="register-page-wrap d-flex align-items-center flex-wrap justify-content-center">
		<div class="container">
			<div class="row align-items-center">
				<div class="col-md-6 col-lg-7">
					<img src="{% static 'vendors/images/register-page-img.png' %}" alt="" />
				</div>
				<div class="col-md-6 col-lg-5">
					<div class="register-box bg-white box-shadow border-radius-10">
						<div class="wizard-content">
							<form class="tab-wizard2 wizard-circle wizard">
								<h5>Basic Account Credentials</h5>
								<section>
									<div class="form-wrap max-width-600 mx-auto">
										<div class="form-group row">
											<label class="col-sm-4 col-form-label">Email Address*</label>
											<div class="col-sm-8">
												<input type="email" class="form-control" />
											</div>
										</div>
										<div class="form-group row">
											<label class="col-sm-4 col-form-label">Username*</label>
											<div class="col-sm-8">
												<input type="text" class="form-control" />
											</div>
										</div>
										<div class="form-group row">
											<label class="col-sm-4 col-form-label">Password*</label>
											<div class="col-sm-8">
												<input type="password" class="form-control" />
											</div>
										</div>
										<div class="form-group row">
											<label class="col-sm-4 col-form-label">Confirm Password*</label>
											<div class="col-sm-8">
												<input type="password" class="form-control" />
											</div>
										</div>
									</div>
								</section>
								<!-- Step 2 -->
								<h5>Personal Information</h5>
								<section>
									<div class="form-wrap max-width-600 mx-auto">
										<div class="form-group row">
											<label class="col-sm-4 col-form-label">Full Name*</label>
											<div class="col-sm-8">
												<input type="text" class="form-control" />
											</div>
										</div>
										<div class="form-group row align-items-center">
											<label class="col-sm-4 col-form-label">Gender*</label>
											<div class="col-sm-8">
												<div class="custom-control custom-radio custom-control-inline pb-0">
													<input type="radio" id="male" name="gender" class="custom-control-input" />
													<label class="custom-control-label" for="male">Male</label>
												</div>
												<div class="custom-control custom-radio custom-control-inline pb-0">
													<input type="radio" id="female" name="gender" class="custom-control-input" />
													<label class="custom-control-label" for="female">Female</label>
												</div>
											</div>
										</div>
										<div class="form-group row">
											<label class="col-sm-4 col-form-label">City</label>
											<div class="col-sm-8">
												<input type="text" class="form-control" />
											</div>
										</div>
										<div class="form-group row">
											<label class="col-sm-4 col-form-label">State</label>
											<div class="col-sm-8">
												<input type="text" class="form-control" />
											</div>
										</div>
									</div>
								</section>
								<!-- Step 3 -->
								<h5>Payment Method & Info</h5>
								<section>
									<div class="form-wrap max-width-600 mx-auto">
										<div class="form-group row">
											<label class="col-sm-4 col-form-label">Credit Card Type</label>
											<div class="col-sm-8">
												<select class="form-control selectpicker" title="Select Card Type">
													<option value="1">Option 1</option>
													<option value="2">Option 2</option>
													<option value="3">Option 3</option>
												</select>
											</div>
										</div>
										<div class="form-group row align-items-center">
											<label class="col-sm-4 col-form-label">Credit Card Number</label>
											<div class="col-sm-8">
												<input type="text" class="form-control" />
											</div>
										</div>
										<div class="form-group row">
											<label class="col-sm-4 col-form-label">CVC</label>
											<div class="col-sm-3">
												<input type="text" class="form-control" />
											</div>
										</div>
										<div class="form-group row">
											<label class="col-sm-4 col-form-label">Expiration Date</label>
											<div class="col-sm-8">
												<div class="row">
													<div class="col-6">
														<select class="form-control selectpicker" title="Month" data-size="5">
															<option value="01">January</option>
															<option value="02">February</option>
															<option value="03">March</option>
															<option value="04">April</option>
															<option value="05">May</option>
															<option value="06">June</option>
															<option value="07">July</option>
															<option value="08">August</option>
															<option value="09">September</option>
															<option value="10">October</option>
															<option value="11">November</option>
															<option value="12">December</option>
														</select>
													</div>
													<div class="col-6">
														<select class="form-control selectpicker" title="Year" data-size="5">
															<option>2020</option>
															<option>2019</option>
															<option>2018</option>
															<option>2017</option>
															<option>2016</option>
															<option>2015</option>
															<option>2014</option>
															<option>2013</option>
															<option>2012</option>
															<option>2011</option>
															<option>2010</option>
															<option>2009</option>
														</select>
													</div>
												</div>
											</div>
										</div>
									</div>
								</section>
								<!-- Step 4 -->
								<h5>Overview Information</h5>
								<section>
									<div class="form-wrap max-width-600 mx-auto">
										<ul class="register-info">
											<li>
												<div class="row">
													<div class="col-sm-4 weight-600">Email Address</div>
													<div class="col-sm-8">example@abc.com</div>
												</div>
											</li>
											<li>
												<div class="row">
													<div class="col-sm-4 weight-600">Username</div>
													<div class="col-sm-8">Example</div>
												</div>
											</li>
											<li>
												<div class="row">
													<div class="col-sm-4 weight-600">Password</div>
													<div class="col-sm-8">.....000</div>
												</div>
											</li>
											<li>
												<div class="row">
													<div class="col-sm-4 weight-600">Full Name</div>
													<div class="col-sm-8">john smith</div>
												</div>
											</li>
											<li>
												<div class="row">
													<div class="col-sm-4 weight-600">Location</div>
													<div class="col-sm-8">123 Example</div>
												</div>
											</li>
										</ul>
										<div class="custom-control custom-checkbox mt-4">
											<input type="checkbox" class="custom-control-input" id="customCheck1" />
											<label class="custom-control-label" for="customCheck1">I have read and agreed to the terms of
												services and
												privacy policy</label>
										</div>
									</div>
								</section>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- success Popup html Start -->
	<button type="button" id="success-modal-btn" hidden data-toggle="modal" data-target="#success-modal"
		data-backdrop="static">
		Launch modal
	</button>
	<div class="modal fade" id="success-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
		aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered max-width-400" role="document">
			<div class="modal-content">
				<div class="modal-body text-center font-18">
					<h3 class="mb-20">Form Submitted!</h3>
					<div class="mb-30 text-center">
						<img src="{% static 'vendors/images/success.png' %}" />
					</div>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
					eiusmod
				</div>
				<div class="modal-footer justify-content-center">
					<a href="{% url 'theme:login' %}" class="btn btn-primary">Done</a>
				</div>
			</div>
		</div>
	</div>
	<!-- success Popup html End -->

	{% include 'mock/includes/modal.html' %}

	<!-- js -->
	<script src="{% static 'vendors/scripts/core.js' %}"></script>
	<script src="{% static 'vendors/scripts/script.min.js' %}"></script>
	<script src="{% static 'vendors/scripts/process.js' %}"></script>
	<script src="{% static 'vendors/scripts/layout-settings.js' %}"></script>
	<script src="{% static 'src/plugins/jquery-steps/jquery.steps.js' %}"></script>
	<script src="{% static 'vendors/scripts/steps-setting.js' %}"></script>
</body>
{% endblock 'content' %}

theme/templates/mock/additional_pages/reset-password.html
{% extends 'mock/layouts/auth_base.html' %}
{% load static %}

{% block 'title' %} Reset Password {% endblock 'title' %}


{% block 'css' %}
<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/core.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/icon-font.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/style.css' %}" />
{% endblock 'css' %}

{% block 'content' %}
<body>
	<div class="login-header box-shadow">
		<div class="container-fluid d-flex justify-content-between align-items-center">
			<div class="brand-logo">
				<a href="{% url 'theme:login' %}">
					<img src="{% static 'vendors/images/deskapp-logo.svg' %}" alt="" />
				</a>
			</div>
			<div class="login-menu">
				<ul>
					<li><a href="{% url 'theme:login' %}">Login</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="login-wrap d-flex align-items-center flex-wrap justify-content-center">
		<div class="container">
			<div class="row align-items-center">
				<div class="col-md-6">
					<img src="{% static 'vendors/images/forgot-password.png' %}" alt="" />
				</div>
				<div class="col-md-6">
					<div class="login-box bg-white box-shadow border-radius-10">
						<div class="login-title">
							<h2 class="text-center text-primary">Reset Password</h2>
						</div>
						<h6 class="mb-20">Enter your new password, confirm and submit</h6>
						<form>
							<div class="input-group custom">
								<input type="text" class="form-control form-control-lg" placeholder="New Password" />
								<div class="input-group-append custom">
									<span class="input-group-text"><i class="dw dw-padlock1"></i></span>
								</div>
							</div>
							<div class="input-group custom">
								<input type="text" class="form-control form-control-lg" placeholder="Confirm New Password" />
								<div class="input-group-append custom">
									<span class="input-group-text"><i class="dw dw-padlock1"></i></span>
								</div>
							</div>
							<div class="row align-items-center">
								<div class="col-5">
									<div class="input-group mb-0">
										<!--
											use code for form submit
											<input class="btn btn-primary btn-lg btn-block" type="submit" value="Submit">
										-->
										<a class="btn btn-primary btn-lg btn-block" href="{% url 'theme:index' %}">Submit</a>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

	{% include 'mock/includes/modal.html' %}
	
	<!-- js -->
	<script src="{% static 'vendors/scripts/core.js' %}"></script>
	<script src="{% static 'vendors/scripts/script.min.js' %}"></script>
	<script src="{% static 'vendors/scripts/process.js' %}"></script>
	<script src="{% static 'vendors/scripts/layout-settings.js' %}"></script>
</body>
{% endblock 'content' %}