project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]
##################################################
from django.urls import include

urlpatterns += [
    path('theme/', include('theme.urls')),
]

theme/urls.py
from django.urls import path
from theme.views import *


app_name = 'theme'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('index2', IndexView2.as_view(), name='index2'),
    path('index3', IndexView3.as_view(), name='index3'),

    path('error_400', ErrorPage400View.as_view(), name='error_400'),
    path('error_403', ErrorPage403View.as_view(), name='error_403'),
    path('error_404', ErrorPage404View.as_view(), name='error_404'),
    path('error_500', ErrorPage500View.as_view(), name='error_500'),
    path('error_503', ErrorPage503View.as_view(), name='error_503'),

    path('form_basic', FormBasicView.as_view(), name='form_basic'),
    path('advanced_component', FormAdvanceComponentView.as_view(), name='advanced_component'),
    path('form_wizard', FormWizardView.as_view(), name='form_wizard'),
    path('html5_editor', FormHtml5EditorView.as_view(), name='html5_editor'),
    path('form_pickers', FormPickersView.as_view(), name='form_pickers'),
    path('image_cropper', FormImageCropperView.as_view(), name='image_cropper'),
    path('image_dropzone', FormImageDropzoneView.as_view(), name='image_dropzone'),

    path('basic_table', TableBasicView.as_view(), name='basic_table'),
    path('datatable', TableDataView.as_view(), name='datatable'),

    path('calendar', CalendarView.as_view(), name='calendar'),

    path('ui_buttons', UIButtonsView.as_view(), name='ui_buttons'),
    path('ui_cards', UICardsView.as_view(), name='ui_cards'),
    path('ui_cards_hover', UICardsHoverView.as_view(), name='ui_cards_hover'),
    path('ui_modals', UIModalsView.as_view(), name='ui_modals'),
    path('ui_tabs', UITabsView.as_view(), name='ui_tabs'),
    path('ui_tooltip_popover', UITooltipPopoverView.as_view(), name='ui_tooltip_popover'),
    path('ui_sweet_alert', UISweetAlertView.as_view(), name='ui_sweet_alert'),
    path('ui_notification', UINotificationView.as_view(), name='ui_notification'),
    path('ui_timeline', UITimelineView.as_view(), name='ui_timeline'),
    path('ui_progressbar', UIProgressbarView.as_view(), name='ui_progressbar'),
    path('ui_typography', UITypographyView.as_view(), name='ui_typography'),
    path('ui_list_group', UIListGroupView.as_view(), name='ui_list_group'),
    path('ui_range_slider', UIRangeSliderView.as_view(), name='ui_range_slider'),
    path('ui_carousel', UICarouselView.as_view(), name='ui_carousel'),

    path('icon_bootstrap', IconBootstrapView.as_view(), name='icon_bootstrap'),
    path('icon_font_awesome', IconFontAwesomeView.as_view(), name='icon_font_awesome'),
    path('icon_foundation', IconFoundationView.as_view(), name='icon_foundation'),
    path('icon_ionicons', IconIoniconsView.as_view(), name='icon_ionicons'),
    path('icon_themify', IconThemifyView.as_view(), name='icon_themify'),
    path('icon_custom', IconCustomView.as_view(), name='icon_custom'),

    path('highchart', HighchartView.as_view(), name='highchart'),
    path('knobchart', KnobchartView.as_view(), name='knobchart'),
    path('jvectormap', JvectormapView.as_view(), name='jvectormap'),
    path('apexchart', ApexchartView.as_view(), name='apexchart'),

    path('chat', ChatView.as_view(), name='chat'),

    path('invoice', InvoiceView.as_view(), name='invoice'),

    path('sitemap', SitemapView.as_view(), name='sitemap'),
    
    path('comming_soon', CommingSoonView.as_view(), name='comming_soon'),

    path('introduction', IntroductionView.as_view(), name='introduction'),
    path('getting_started', GettingStartedView.as_view(), name='getting_started'),
    path('color_settings', ColorSettingsView.as_view(), name='color_settings'),
    path('third_party_plugins', ThirdPartyPluginsView.as_view(), name='third_party_plugins'),

    path('login', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('forgot_password', ForgotPasswordView.as_view(), name='forgot_password'),
    path('reset_password', ResetPasswordView.as_view(), name='reset_password'),
]

theme/views.py
from django.views.generic import TemplateView
from django.shortcuts import HttpResponse

class IndexView(TemplateView):
    template_name = 'mock/dashboards/index.html'

class IndexView2(TemplateView):
    template_name = 'mock/dashboards/index2.html'

class IndexView3(TemplateView):
    template_name = 'mock/dashboards/index3.html'


class ErrorPage400View(TemplateView):
    template_name = 'mock/error_pages/400.html'

class ErrorPage403View(TemplateView):
    template_name = 'mock/error_pages/403.html'

class ErrorPage404View(TemplateView):
    template_name = 'mock/error_pages/404.html'

class ErrorPage500View(TemplateView):
    template_name = 'mock/error_pages/500.html'

class ErrorPage503View(TemplateView):
    template_name = 'mock/error_pages/503.html'


class FormBasicView(TemplateView):
    template_name = 'mock/forms/form-basic.html'

class FormAdvanceComponentView(TemplateView):
    template_name = 'mock/forms/advanced-components.html'

class FormWizardView(TemplateView):
    template_name = 'mock/forms/form-wizard.html'

class FormHtml5EditorView(TemplateView):
    template_name = 'mock/forms/html5-editor.html'

class FormPickersView(TemplateView):
    template_name = 'mock/forms/form-pickers.html'

class FormImageCropperView(TemplateView):
    template_name = 'mock/forms/image-cropper.html'
    
class FormImageDropzoneView(TemplateView):
    template_name = 'mock/forms/image-dropzone.html'

    def post(self, request, *args, **kwargs):
        return HttpResponse('123123')
    

class TableBasicView(TemplateView):
    template_name = 'mock/tables/basic-table.html'

class TableDataView(TemplateView):
    template_name = 'mock/tables/datatable.html'


class CalendarView(TemplateView):
    template_name = 'mock/calendar/calendar.html'


class UIButtonsView(TemplateView):
    template_name = 'mock/ui_elements/ui-buttons.html'

class UICardsView(TemplateView):
    template_name = 'mock/ui_elements/ui-cards.html'

class UICardsHoverView(TemplateView):
    template_name = 'mock/ui_elements/ui-cards-hover.html'

class UIModalsView(TemplateView):
    template_name = 'mock/ui_elements/ui-modals.html'

class UITabsView(TemplateView):
    template_name = 'mock/ui_elements/ui-tabs.html'

class UITooltipPopoverView(TemplateView):
    template_name = 'mock/ui_elements/ui-tooltip-popover.html'

class UISweetAlertView(TemplateView):
    template_name = 'mock/ui_elements/ui-sweet-alert.html'

class UINotificationView(TemplateView):
    template_name = 'mock/ui_elements/ui-notification.html'

class UITimelineView(TemplateView):
    template_name = 'mock/ui_elements/ui-timeline.html'

class UIProgressbarView(TemplateView):
    template_name = 'mock/ui_elements/ui-progressbar.html'

class UITypographyView(TemplateView):
    template_name = 'mock/ui_elements/ui-typography.html'

class UIListGroupView(TemplateView):
    template_name = 'mock/ui_elements/ui-list-group.html'

class UIRangeSliderView(TemplateView):
    template_name = 'mock/ui_elements/ui-range-slider.html'

class UICarouselView(TemplateView):
    template_name = 'mock/ui_elements/ui-carousel.html'


class IconBootstrapView(TemplateView):
    template_name = 'mock/icons/bootstrap-icon.html'

class IconFontAwesomeView(TemplateView):
    template_name = 'mock/icons/font-awesome.html'

class IconFoundationView(TemplateView):
    template_name = 'mock/icons/foundation.html'

class IconIoniconsView(TemplateView):
    template_name = 'mock/icons/ionicons.html'

class IconThemifyView(TemplateView):
    template_name = 'mock/icons/themify.html'

class IconCustomView(TemplateView):
    template_name = 'mock/icons/custom-icon.html'


class HighchartView(TemplateView):
    template_name = 'mock/charts/highchart.html'

class KnobchartView(TemplateView):
    template_name = 'mock/charts/knob-chart.html'

class JvectormapView(TemplateView):
    template_name = 'mock/charts/jvectormap.html'

class ApexchartView(TemplateView):
    template_name = 'mock/charts/apexcharts.html'


class ChatView(TemplateView):
    template_name = 'mock/chat/chat.html'


class InvoiceView(TemplateView):
    template_name = 'mock/invoice/invoice.html'

class SitemapView(TemplateView):
    template_name = 'mock/sitemap/sitemap.html'

class CommingSoonView(TemplateView):
    template_name = 'mock/comming_soon.html'


class IntroductionView(TemplateView):
    template_name = 'mock/documentation/introduction.html'

class GettingStartedView(TemplateView):
    template_name = 'mock/documentation/getting-started.html'

class ColorSettingsView(TemplateView):
    template_name = 'mock/documentation/color-settings.html'

class ThirdPartyPluginsView(TemplateView):
    template_name = 'mock/documentation/third-party-plugins.html'


class LoginView(TemplateView):
    template_name = 'mock/additional_pages/login.html'

class RegisterView(TemplateView):
    template_name = 'mock/additional_pages/register.html'

class ForgotPasswordView(TemplateView):
    template_name = 'mock/additional_pages/forgot-password.html'

class ResetPasswordView(TemplateView):
    template_name = 'mock/additional_pages/reset-password.html'

theme/templates/mock/sitemap/sitemap.html
{% extends 'mock/layouts/base.html' %}
{% load static %}

{% block 'title' %} Sitemap {% endblock 'title' %}


{% block 'css' %}
<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/core.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/icon-font.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/style.css' %}" />
{% endblock 'css' %}

{% block 'script' %}
<script src="{% static 'vendors/scripts/core.js' %}"></script>
<script src="{% static 'vendors/scripts/script.min.js' %}"></script>
<script src="{% static 'vendors/scripts/process.js' %}"></script>
<script src="{% static 'vendors/scripts/layout-settings.js' %}"></script>
{% endblock 'script' %}

{% block 'content' %}
<div class="pd-ltr-20 xs-pd-20-10">
	<div class="min-height-200px">
		<div class="page-header">
			<div class="row">
				<div class="col-md-12 col-sm-12">
					<div class="title">
						<h4>Sitemap</h4>
					</div>
					<nav aria-label="breadcrumb" role="navigation">
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="{% url 'theme:index' %}">Home</a></li>
							<li class="breadcrumb-item active" aria-current="page">
								Sitemap
							</li>
						</ol>
					</nav>
				</div>
			</div>
		</div>
		<div class="mb-30">
			<div class="pb-20">
				<div class="row">
					<div class="col-lg-2 col-md-6 col-sm-12">
						<div class="sitemap">
							<h5 class="h5">Home</h5>
							<ul>
								<li><a href="{% url 'theme:index' %}">Dashboard style 1</a></li>
								<li><a href="{% url 'theme:index2' %}">Dashboard style 2</a></li>
								<li><a href="{% url 'theme:index3' %}">Dashboard style 3</a></li>
							</ul>
						</div>
						<div class="sitemap">
							<h5 class="h5">Forms</h5>
							<ul>
								<li><a href="{% url 'theme:form_basic' %}">Form Basic</a></li>
								<li><a href="{% url 'theme:advanced_component' %}">Advanced Components</a></li>
								<li><a href="{% url 'theme:form_wizard' %}">Form Wizard</a></li>
								<li><a href="{% url 'theme:html5_editor' %}">HTML5 Editor</a></li>
								<li><a href="{% url 'theme:form_pickers' %}">Form Pickers</a></li>
								<li><a href="{% url 'theme:image_cropper' %}">Image Cropper</a></li>
								<li><a href="{% url 'theme:image_dropzone' %}">Image Dropzone</a></li>
							</ul>
						</div>
						<div class="sitemap">
							<h5 class="h5">Calendar</h5>
							<ul>
								<li><a href="{% url 'theme:calendar' %}">Calendar</a></li>
							</ul>
						</div>
						<div class="sitemap">
							<h5 class="h5">Invoice</h5>
							<ul>
								<li><a href="{% url 'theme:invoice' %}">Invoice</a></li>
							</ul>
						</div>
						<div class="sitemap">
							<h5 class="h5">Chat Module</h5>
							<ul>
								<li><a href="{% url 'theme:chat' %}">Chat</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-2 col-md-6 col-sm-12">
						<div class="sitemap">
							<h5 class="h5">Icons</h5>
							<ul>
								<li><a href="{% url 'theme:icon_bootstrap' %}">Bootstrap Icons</a></li>
								<li><a href="{% url 'theme:icon_font_awesome' %}">FontAwesome Icons</a></li>
								<li><a href="{% url 'theme:icon_foundation' %}">Foundation Icons</a></li>
								<li><a href="{% url 'theme:icon_ionicons' %}">Ionicons Icons</a></li>
								<li><a href="{% url 'theme:icon_themify' %}">Themify Icons</a></li>
								<li><a href="{% url 'theme:icon_custom' %}">Custom Icons</a></li>
							</ul>
						</div>
						<div class="sitemap">
							<h5 class="h5">Charts</h5>
							<ul>
								<li><a href="{% url 'theme:highchart' %}">Highchart</a></li>
								<li><a href="{% url 'theme:knobchart' %}">jQuery Knob</a></li>
								<li><a href="{% url 'theme:jvectormap' %}">jvectormap</a></li>
								<li><a href="{% url 'theme:apexchart' %}">Apexchart</a></li>
							</ul>
						</div>
						<div class="sitemap">
							<h5 class="h5">Error Pages</h5>
							<ul>
								<li><a href="{% url 'theme:error_400' %}">400</a></li>
								<li><a href="{% url 'theme:error_403' %}">403</a></li>
								<li><a href="{% url 'theme:error_404' %}">404</a></li>
								<li><a href="{% url 'theme:error_500' %}">500</a></li>
								<li><a href="{% url 'theme:error_503' %}">503</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-2 col-md-6 col-sm-12">
						<div class="sitemap">
							<h5 class="h5">Tables</h5>
							<ul>
								<li><a href="{% url 'theme:basic_table' %}">Basic Tables</a></li>
								<li><a href="{% url 'theme:datatable' %}">DataTables</a></li>
							</ul>
						</div>
						<div class="sitemap">
							<h5 class="h5">UI Elements</h5>
							<ul>
								<li><a href="{% url 'theme:ui_buttons' %}">Buttons</a></li>
								<li><a href="{% url 'theme:ui_cards' %}">Cards</a></li>
								<li><a href="{% url 'theme:ui_cards_hover' %}">Cards Hover</a></li>
								<li><a href="{% url 'theme:ui_modals' %}">Modals</a></li>
								<li><a href="{% url 'theme:ui_tabs' %}">Tabs</a></li>
								<li><a href="{% url 'theme:ui_tooltip_popover' %}">Tooltip &amp; Popover</a></li>
								<li><a href="{% url 'theme:ui_sweet_alert' %}">Sweet Alert</a></li>
								<li><a href="{% url 'theme:ui_notification' %}">Notification</a></li>
								<li><a href="{% url 'theme:ui_timeline' %}">Timeline</a></li>
								<li><a href="{% url 'theme:ui_progressbar' %}">Progressbar</a></li>
								<li><a href="{% url 'theme:ui_typography' %}">Typography</a></li>
								<li><a href="{% url 'theme:ui_list_group' %}">List group</a></li>
								<li><a href="{% url 'theme:ui_range_slider' %}">Range slider</a></li>
								<li><a href="{% url 'theme:ui_carousel' %}">Carousel</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-2 col-md-6 col-sm-12">
						<div class="sitemap">
							<h5 class="h5">Additional Pages</h5>
							<ul>
								<li><a href="{% url 'theme:index' %}">Login</a></li>
								<li><a href="{% url 'theme:index' %}">Reigster</a></li>
								<li><a href="{% url 'theme:index' %}">Forgot Password</a></li>
								<li><a href="{% url 'theme:index' %}">Reset Password</a></li>
							</ul>
						</div>
						<div class="sitemap">
							<h5 class="h5">Extra Pages</h5>
							<ul>
								<li><a href="{% url 'theme:index' %}">Blank</a></li>
								<li><a href="{% url 'theme:index' %}">Contact Directory</a></li>
								<li><a href="{% url 'theme:index' %}">Blog</a></li>
								<li><a href="{% url 'theme:index' %}">Blog Detail</a></li>
								<li><a href="{% url 'theme:index' %}">Product</a></li>
								<li><a href="{% url 'theme:index' %}">Product Detail</a></li>
								<li><a href="{% url 'theme:index' %}">FAQ</a></li>
								<li><a href="{% url 'theme:index' %}">Profile</a></li>
								<li><a href="{% url 'theme:index' %}">Gallery</a></li>
								<li><a href="{% url 'theme:index' %}">Pricing Tables</a></li>
								<li><a href="{% url 'theme:index' %}">Video Player</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-2 col-md-6 col-sm-12">
						<div class="sitemap">
							<h5 class="h5">Sitemap</h5>
							<ul>
								<li><a href="{% url 'theme:sitemap' %}">Sitemap</a></li>
							</ul>
						</div>
						<div class="sitemap">
							<h5 class="h5">Documentation</h5>
							<ul>
								<li><a href="{% url 'theme:index' %}">Introduction</a></li>
								<li><a href="{% url 'theme:index' %}">Getting started</a></li>
								<li><a href="{% url 'theme:index' %}">Color settings</a></li>
								<li><a href="{% url 'theme:index' %}">Third party plugins</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-2 col-md-6 col-sm-12">
						<div class="sitemap">
							<h5 class="h5">Multi Level Sitemap</h5>
							<ul>
								<li><a href="#">Level 1</a></li>
								<li><a href="#">Level 1</a></li>
								<li class="child">
									<h5 class="h5">Level 2</h5>
									<ul>
										<li><a href="#">Level 2</a></li>
										<li><a href="#">Level 2</a></li>
										<li class="child">
											<h5 class="h5">Level 3</h5>
											<ul>
												<li><a href="#">Level 3</a></li>
												<li><a href="#">Level 3</a></li>
											</ul>
										</li>
									</ul>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="row"></div>
			</div>
		</div>
	</div>
	<div class="footer-wrap pd-20 mb-20 card-box">
		DeskApp - Bootstrap 4 Admin Template By
		<a href="https://github.com/dropways" target="_blank">Ankit Hingarajiya</a>
	</div>
</div>
{% endblock 'content' %}